/* Generated By:JavaCC: Do not edit this line. WhileParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface WhileParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int POSINT = 8;
  /** RegularExpression Id. */
  int NEGINT = 9;
  /** RegularExpression Id. */
  int LPAREN = 10;
  /** RegularExpression Id. */
  int RPAREN = 11;
  /** RegularExpression Id. */
  int PROC = 12;
  /** RegularExpression Id. */
  int TRUE = 13;
  /** RegularExpression Id. */
  int FALSE = 14;
  /** RegularExpression Id. */
  int NOT = 15;
  /** RegularExpression Id. */
  int LBRACE = 16;
  /** RegularExpression Id. */
  int RBRACE = 17;
  /** RegularExpression Id. */
  int SEMICOLON = 18;
  /** RegularExpression Id. */
  int ASSIGN = 19;
  /** RegularExpression Id. */
  int AND = 20;
  /** RegularExpression Id. */
  int OR = 21;
  /** RegularExpression Id. */
  int LESSTHAN = 22;
  /** RegularExpression Id. */
  int GREATERTHAN = 23;
  /** RegularExpression Id. */
  int EQUALS = 24;
  /** RegularExpression Id. */
  int DIV = 25;
  /** RegularExpression Id. */
  int PLUS = 26;
  /** RegularExpression Id. */
  int MINUS = 27;
  /** RegularExpression Id. */
  int TIMES = 28;
  /** RegularExpression Id. */
  int COMMA = 29;
  /** RegularExpression Id. */
  int ELSE = 30;
  /** RegularExpression Id. */
  int IF = 31;
  /** RegularExpression Id. */
  int WHILE = 32;
  /** RegularExpression Id. */
  int RETURN = 33;
  /** RegularExpression Id. */
  int IN = 34;
  /** RegularExpression Id. */
  int OUT = 35;
  /** RegularExpression Id. */
  int ID = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "<POSINT>",
    "<NEGINT>",
    "\"(\"",
    "\")\"",
    "\"proc\"",
    "\"true\"",
    "\"false\"",
    "\"!\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"=\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\",\"",
    "\"else\"",
    "\"if\"",
    "\"while\"",
    "\"return\"",
    "\"in\"",
    "\"out\"",
    "<ID>",
  };

}
